name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

      - name: Echo
        run: |
          echo "New release created: ${{ steps.release.outputs.tag_name }}"
          echo "TOC: $(cat TransmogCleaner.toc | grep "^## Version:")"

      - name: Zip Addon Folder
        run: |
          mkdir build
          zip -r build/TransmogCleaner-${{ steps.release.outputs.tag_name }}.zip Media *.lua *.toc *.xml
