name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

      - name: Update .toc Version
        if: ${{ steps.release.outputs.tag_name != '' }}
        run: |
          VERSION=${{ steps.release.outputs.tag_name }}
          VERSION=${VERSION#v}
          sed -i "s/^## Version: .*/## Version: $VERSION/" TransmogCleaner.toc

      - name: Echo
        if: ${{ steps.release.outputs.tag_name != '' }}  
        run: |
          echo "New release created: ${{ steps.release.outputs.tag_name }}"
          echo "TOC: $(cat TransmogCleaner.toc | grep "^## Version:")"

      - name: Zip Addon Folder
        if: ${{ steps.release.outputs.tag_name != '' }}  
        run: |
          mkdir build
          zip -r build/TransmogCleaner-${{ steps.release.outputs.tag_name }}.zip Media *.lua *.toc *.xml
          
      - name: Upload Release Asset to CurseForge
        uses: itsmeow/curseforge-upload@v3
        if: ${{ steps.release.outputs.tag_name != '' }}  
        with:
          file_path: build/TransmogCleaner-${{ steps.release.outputs.tag_name }}.zip
          project_id: "1299627"
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          game_endpoint: wow
          game_versions: "13203,13433"
          changelog: ${{ steps.release.outputs.release_notes }}
          changelog_type: markdown

